[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
risc0-build = { version = "^2.1.0" }

[package.metadata.risc0]
methods = ["guest"]
